name: Continuous Integration for Development Environment

env:
  CONTEXT_DIR: './'
  DOCKERFILE: Dockerfile
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  IMAGE_NAME: ${{ github.repository }}/development

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Create environment variables
        run: |
          echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME" >> $GITHUB_ENV
          export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME
          echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$GITHUB_SHA-gitsha" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub's Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            VERSION=${{ github.sha }}
          context: .
          no-cache: true
          platforms: linux/arm64
          push: true
          tags: ${{ env.FULL_IMAGE_NAME }}

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@main
        with:
          server: ${{ secrets.CAPROVER_DEVELOPMENT_HOST }}
          app: ${{ secrets.CAPROVER_APP }}
          token: '${{ secrets.CAPROVER_DEVELOPMENT_APP_TOKEN }}'
          image: '${{ env.FULL_IMAGE_NAME }}'

